# Generated by Django 3.1.7 on 2021-03-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursus',
            name='year_from_bac',
            field=models.SmallIntegerField(blank=True, default='', help_text='Annee depuis le bac :', max_length=255, verbose_name='Year from BAC :'),
        ),
    ]
