# Generated by Django 3.1.5 on 2021-04-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_auto_20210316_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(default='', verbose_name='Date of birth :')),
                ('last_name', models.CharField(default='???', help_text='nom de famille de l etudiant', max_length=50, verbose_name='Last Name :')),
                ('phone_number', models.CharField(blank=True, default='0123456789', help_text='numero de telephone', max_length=10, verbose_name='Phone number :')),
                ('email', models.CharField(default='???@???.com', help_text='Courriel', max_length=255, verbose_name='Email :')),
                ('comments', models.CharField(blank=True, default='', help_text='Commentaires :', max_length=255, verbose_name='Comments :')),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AddField(
            model_name='cursus',
            name='scholar_year',
            field=models.CharField(default='0000-0001', help_text='Annee scolaire :', max_length=9, null=True, verbose_name='Scholar year :'),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='name',
            field=models.CharField(default='aucun', help_text='Nom du cursus :', max_length=50, null=True, verbose_name='Cursus Name :'),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='year_from_bac',
            field=models.SmallIntegerField(default=0, help_text='Annee depuis le bac :', null=True, verbose_name='Year from BAC :'),
        ),
        migrations.AddField(
            model_name='student',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='lycee.cursus'),
        ),
    ]
