# Generated by Django 3.1.5 on 2021-04-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0005_auto_20210410_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Prenom :'),
        ),
    ]
