# Generated by Django 3.1.5 on 2021-04-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0006_auto_20210410_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cause', models.CharField(blank=True, default='Injustifie', max_length=255, verbose_name='cause de l absence')),
                ('date', models.DateField(verbose_name='dates')),
                ('ismissing', models.BooleanField(default=True)),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.student')),
            ],
        ),
    ]
